require('packer_init')

require('core.options')
require('core.keymaps')
require('core.colorscheme')

require('lsp.nvim-lspconfig')
require('lsp.cmp-nvim-lsp')
require('lsp.cmp')

require('plugins.tokyonight')
require('plugins.kanagawa')
require('plugins.catppuccin')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.toggleterm')
require('plugins.telescope')
require('plugins.comment')
require('plugins.nvim-autopairs')
require('plugins.indent-blankline')
require('plugins.nvim-treesitter')
